### ISSUE TITLE
Suggestion: Change Title Colour

### ISSUE THREAD

**Issue by JMasiano** [TransientEnigma/github-crash-course#1]
I think it looks better if the main title is a bit more orange.

The styling rule could be changed like this:

```css
h1 {
  color: #d99319;
}
```
